test_0 (__main__.lab2a.test_0)
[Lab 2] - [Investigation 1] - [Part 1] - variables & printing - Test for file creation: ./lab2a.py ... ok
test_1 (__main__.lab2a.test_1)
[Lab 2] - [Investigation 1] - [Part 1] - variables & printing - Test for errors running: ./lab2a.py ... /usr/lib64/python3.11/subprocess.py:822: ResourceWarning: unclosed file <_io.TextIOWrapper name=3 encoding='UTF-8'>
  _cleanup()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
ok
test_2 (__main__.lab2a.test_2)
[Lab 2] - [Investigation 1] - [Part 1] - variables & printing - Test for correct shebang line: ./lab2a.py ... ok
test_3 (__main__.lab2a.test_3)
[Lab 2] - [Investigation 1] - [Part 1] - variables & printing - Test for correct output: ./lab2a.py ... ok
test_0 (__main__.lab2b.test_0)
[Lab 2] - [Investigation 1] - [Part 1] - using input() function - Test for file creation: ./lab2b.py ... ok
test_1 (__main__.lab2b.test_1)
[Lab 2] - [Investigation 1] - [Part 1] - using input() - Test for errors with sending input "Jon" "20": ./lab2b.py ... ok
test_2 (__main__.lab2b.test_2)
[Lab 2] - [Investigation 1] - [Part 1] - using input() - Test for correct shebang line: ./lab2b.py ... ok
test_3 (__main__.lab2b.test_3)
[Lab 2] - [Investigation 1] - [Part 1] - using input() - Test output with sending input "Jon" "20": ./lab2b.py ... ok
test_4 (__main__.lab2b.test_4)
[Lab 2] - [Investigation 1] - [Part 1] - using input() - Test output with sending input "Jen" "25": ./lab2b.py ... ok
test_0 (__main__.lab2c.test_0)
[Lab 2] - [Investigation 1] - [Part 2] - command line arguments - Test for file creation: ./lab2c.py ... ok
test_1 (__main__.lab2c.test_1)
[Lab 2] - [Investigation 1] - [Part 2] - command line arguments - Test for errors with 2 args: ./lab2c.py Jon 20 ... ok
test_2 (__main__.lab2c.test_2)
[Lab 2] - [Investigation 1] - [Part 2] - command line arguments - Test for correct shebang line: ./lab2c.py ... ok
test_3 (__main__.lab2c.test_3)
[Lab 2] - [Investigation 1] - [Part 2] - command line arguments - Test output for: ./lab2c.py Jon 20 ... ok
test_4 (__main__.lab2c.test_4)
[Lab 2] - [Investigation 1] - [Part 2] - command line arguments - Test output for: ./lab2c.py Jen 25 ... ok
test_0 (__main__.lab2d.test_0)
[Lab 2] - [Investigation 2] - [Part 1] - sys.argv and if - Test for file creation: ./lab2d.py ... ok
test_1 (__main__.lab2d.test_1)
[Lab 2] - [Investigation 2] - [Part 1] - sys.argv and if - Test for errors with 0 args: ./lab2d.py ... ok
test_2 (__main__.lab2d.test_2)
[Lab 2] - [Investigation 2] - [Part 1] - sys.argv and if - Test for correct shebang line: ./lab2d.py ... ok
test_3 (__main__.lab2d.test_3)
[Lab 2] - [Investigation 2] - [Part 1] - sys.argv and if - Test for errors: ./lab2d.py Jon ... ok
test_4 (__main__.lab2d.test_4)
[Lab 2] - [Investigation 2] - [Part 1] - sys.argv and if - Test for errors: ./lab2d.py Jon 20 ... ok
test_5 (__main__.lab2d.test_5)
[Lab 2] - [Investigation 2] - [Part 1] - sys.argv and if - Test for errors: ./lab2d.py Jon 20 More ... ok
test_6 (__main__.lab2d.test_6)
[Lab 2] - [Investigation 2] - [Part 1] - sys.argv and if - Test output with 0 args: ./lab2d.py ... ok
test_7 (__main__.lab2d.test_7)
[Lab 2] - [Investigation 2] - [Part 1] - sys.argv and if - Test output with 1 args: ./lab2d.py Jon ... ok
test_8 (__main__.lab2d.test_8)
[Lab 2] - [Investigation 2] - [Part 1] - sys.argv and if - Test output with 2 args: ./lab2d.py Jon 20 ... ok
test_9 (__main__.lab2d.test_9)
[Lab 2] - [Investigation 2] - [Part 1] - sys.argv and if - Test output with 3 args: ./lab2d.py Jon 20 More ... ok
test_0 (__main__.lab2e.test_0)
[Lab 2] - [Investigation 3] - [Part 1] - while loop with timer 10 - Test for file creation: ./lab2e.py ... ok
test_1 (__main__.lab2e.test_1)
[Lab 2] - [Investigation 3] - [Part 1] - while loop with timer 10 - Test for errors: ./lab2e.py ... ok
test_2 (__main__.lab2e.test_2)
[Lab 2] - [Investigation 3] - [Part 1] - while loop with timer 10 - Test for correct shebang line: ./lab2e.py ... ok
test_4 (__main__.lab2e.test_4)
[Lab 2] - [Investigation 3] - [Part 1] - while loop with timer 10 - Test for output: ./lab2e.py ... FAIL

======================================================================
FAIL: test_4 (__main__.lab2e.test_4)
[Lab 2] - [Investigation 3] - [Part 1] - while loop with timer 10 - Test for output: ./lab2e.py
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jhyppolite/ops445/lab2/./CheckLab2.py", line 300, in test_4
    self.assertEqual(stdout, expected_output, msg=error_output)
AssertionError: b'1000000\n999999\n999998\n999997\n999996\n99[7888861 chars]f!\n' != b'10\n9\n8\n7\n6\n5\n4\n3\n2\n1\nblast off!\n' : wrong output (HINT: pay attention to the last number that is displayed, is it a 1 or a 0?)

----------------------------------------------------------------------
Ran 28 tests in 0.914s

FAILED (failures=1)
OPS445 Lab Report - System Information for running ./CheckLab2.py
=================================================================
    User login name: jhyppolite
    Git Email: jhyppolite@myseneca.ca
    Linux system name: fedora
    Python executable: /usr/bin/python3
    Python version:  3.11.9 (main, Apr 17 2024, 00:00:00) [GCC 13.2.1 20240316 (Red Hat 13.2.1-7)]
    OS Platform: linux
    Working Directory: /home/jhyppolite/ops445/lab2
    Start at: Wed May 29 02:25:06 2024
=================================================================
